### ISSUE TITLE
USER STORY: View goods

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecommerce#10]
As a **Site User** I can **view the goods on sale** so that **I can see if there is anything I would want to purchase**

# Acceptance Criteria

 - I can see an image of all products
 - I can see a description of all products
 - I can see the price of all products
 

# Tasks

- [ ] Add products app
- [ ] Add products image, description and price to the database
- [ ] Show all information to the user
