### ISSUE TITLE
USER STORY: Sort the products

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecommerce#11]
As a **Site User** I can **sort the goods on sale by relevant categories** so that **I can see easily navigate the goods**

# Acceptance Criteria

- I can choose a category of goods from the relevant page 
- This displays the goods from the selected category

# Tasks

- [ ] Assign goods to relevant categories
- [ ] Add the categories to the relevant page on the site
- [ ] Manually test viewing all categories
