### ISSUE TITLE
USER STORY: Site security

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecommerce#20]
As a **Site Owner / User** I can **be confident of the sites security** so that **I don't mind adding personal information**

# Acceptance Criteria

 - AC_1
 - AC_2
 - AC_3

# Tasks

- [ ] Make sure no passwords are in the repo
- [ ] Make sure all secret keys are hidden in env var's or the files are in .gitignore
- [ ] Turn off DEBUG before final deployment
