### ISSUE TITLE
USER STORY: Well tested

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecommerce#21]
As a **Site Owner** I can **know that the site is well tested** so that **I am confident that the site works**

# Acceptance Criteria

FIND ACCEPTED TESTING COVERAGE
 - Functionality is well tested
 - Usability is well tested
 - Responsiveness is well tested
 - Data management is well tested

# Tasks

- [ ] Continually test functionality
- [ ] Continually test usability
- [ ] Continually test responsiveness
- [ ] Continually test data management
