### ISSUE TITLE
USER STORY: Search engine optimisation

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecommerce#22]
As a **Site Owner** I can **know that my site has been optimised for search engines** so that **I receive more business**

# Acceptance Criteria

 - All pages can be reached by a link from another findable page
 - Meta Description tags are used
 - Parent template has a relevant title
 - A sitemap is included
 - A robots.txt is included
 - A 404 response page with an appropriate redirect for attempted access to non-existent content is included

# Tasks

- [ ] Make sure all pages can be reached by a link from another findable page
- [ ] Make sure Meta Description tags are used
- [ ] Make sure Parent template has a relevant title
- [ ] Make sure a correct sitemap is included
- [ ] Make sure a correct robots.txt is included
- [ ] Make sure  the 404 response page has an appropriate redirect for attempted access to non-existent content
