### ISSUE TITLE
USER STORY: Newsletter signup

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecommerce#23]
As a **Site User** I can **signup to the newsletter** so that **I can stay up to date with the business**

# Acceptance Criteria

 - I can sign up to the newsletter using my email address
 - I am made aware if signing up was successful or not
 - If not successful I am made aware why

# Tasks

- [ ] Add newsletter signup form
- [ ] Validate entered info
- [ ] Add helpful message on happy/sad root
- [ ] Add signup info to database
